version: '3.7'
services:
  db:
    image: mongo:4.2.3
    ports:
      - target: 27017
        published: 27017
        protocol: tcp
        mode: host
    volumes:
      - type: bind
        source: ./.data
        target: /data
